name: Publish Image to Docker Hub

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Get the git tag version
        id: get_tag_version
        run: echo "::set-output name=tag_version::$(git describe --tags --abbrev=0)"

      - name: Add tag version to HTML file
        run: |
          sed -i 's#<meta name="tag_version" content="VERSION_PLACEHOLDER" />#<meta name="tag_version" content="${{ steps.get_tag_version.outputs.tag_version }}" />#g' index.html

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: |
            pariskwsto/travel-guide-flexbox_one-page-template:${{ env.TAG_NAME }}
            pariskwsto/travel-guide-flexbox_one-page-template:latest
